### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by dyaskur** [ikeq/vite-plugin-filter-replace#1]
I have js file contain below code:

     throw new Error("program has already exited __foo__");
    
I want to replace `program` to `zzz` and `__foo__` to `xxx` I tried below code in vite.config.ts :
```
filterReplace([
      {
        filter: /\.js/,
        replace: [
          {from: /__foo__/g, to: 'xxx'},
          {from: 'program', to: 'zzz'},
        ],
      },
      {apply: 'build'}]),
```

 but doesnt work. the generated file still has same string. What's wrong ?

**Comment by ikeq** [comment]
This plugin currently only works with `apply: serve`, you can use [@rollup/plugin-replace](https://github.com/rollup/plugins/tree/master/packages/replace) for building.

**Comment by ikeq** [comment]
Supported [![npm](https://img.shields.io/npm/v/vite-plugin-filter-replace.svg)](https://npmjs.com/package/vite-plugin-filter-replace).
- `apply: 'build'` -> works with `vite build`
- `apply: 'serve'` -> works with `vite serve`
- leave `apply` blank -> works with both `vite serve` and `vite build`
