### ISSUE TITLE
Import doesn't work.

### ISSUE THREAD

**Issue by NPanayotov** [ikeq/vite-plugin-filter-replace#2]
Hi, there is an issue with the import.

![image](https://user-images.githubusercontent.com/13221604/214065600-563a0213-e15a-41bb-a06d-ec961c0c6a50.png)

Using:

`import filterReplace from 'vite-plugin-filter-replace';`

![image](https://user-images.githubusercontent.com/13221604/214065708-44722a9b-9f5b-4e1c-bbb7-ec594f017445.png)

![image](https://user-images.githubusercontent.com/13221604/214065667-c80cbc95-54ff-4390-8350-b20172a4f750.png)

**Comment by NPanayotov** [comment]
P.S it works if I use the plugin like this:

![image](https://user-images.githubusercontent.com/13221604/214066067-12795cb1-c4a3-4ac8-84e2-bb241b286aef.png)

**Comment by thdoan** [comment]
I'm not able to get this plugin to work in my Vite setup.

When using `import filterReplace from 'vite-plugin-filter-replace';` as shown in the instructions, I get this error:

> TypeError: replace is not a function

When using `import filterReplace from 'vite-plugin-filter-replace';` like above, I get this error:

> TypeError: filterReplace is not a function

When using `import filterReplace from 'vite-plugin-filter-replace';` along with `filterReplace.default()` it builds OK, but I get the eslint error below and the replacement doesn't happen:

> Property 'default' does not exist on type '(replacements?: Replacement[], options?: Options) => Plugin_2'.

UPDATE: I ended up adding this to my `package.json` and it achieves the same result (replacing some string in the bundle):

```
"build": "vite build && sed -i 's/search_string/replace_string/' dist/filename",
```

**Comment by liuyib** [comment]
@ikeq help

**Comment by NPanayotov** [comment]
The docs seem to be updated now. Try:

import replace from 'vite-plugin-filter-replace';

**Comment by jonathanstanley** [comment]
based on the tip from @thdoan above i modified for current docs. this worked:

```diff
  plugins: [
-   replace([
+   replace.default([
      {
        filter: /\.json$/,
        replace: {
          from: /__formula__/g,
          to: "foo",
        },
      },
    ]),
  ],
```

the type linting doesn't show the `default` property. but `console.log(replacer)` outputs an object that just contains a property named `default`.

**Comment by NPanayotov** [comment]
Fixed in latest commit - https://github.com/ikeq/vite-plugin-filter-replace/commit/b2a46729c2f7cd24336356677a8322717a2e9134
